name: Build & Release APK

on:
  push:
    tags: [ 'v*' ]          # 只有打了形如 v1.0.0 的 tag 才触发
  workflow_dispatch:        # 也可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            自动生成 Debug APK，对应 tag `${{ github.ref_name }}`。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
